/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type CloudinaryAsset = {
  _type: "cloudinaryAsset";
  publicId?: string;
  secureUrl?: string;
  format?: string;
  width?: number;
  height?: number;
  duration?: number;
  bytes?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Agent = {
  _id: string;
  _type: "agent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  title?: InternationalizedArrayString;
  email?: string;
  phone: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type JournalPost = {
  _id: string;
  _type: "journalPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  slug: Slug;
  excerpt?: InternationalizedArrayText;
  category: "barrios" | "lifestyle" | "inversion" | "interiorismo" | "guias";
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  video?: CloudinaryAsset;
  videoCaption?: InternationalizedArrayString;
  videoPoster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bodyEs?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  author?: string;
  publishedAt?: string;
  isPublished?: boolean;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote: InternationalizedArrayText;
  attribution: string;
  isPublished?: boolean;
};

export type NeighbourhoodReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "neighbourhood";
};

export type Property = {
  _id: string;
  _type: "property";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  slug: Slug;
  operation: "venta" | "alquiler";
  propertyType: "piso" | "atico" | "casa" | "duplex" | "estudio" | "local";
  neighbourhood: NeighbourhoodReference;
  price: number;
  surface?: number;
  bedrooms?: number;
  bathrooms?: number;
  description?: InternationalizedArrayText;
  highlights?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  isPublic?: boolean;
};

export type Neighbourhood = {
  _id: string;
  _type: "neighbourhood";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  blurb?: InternationalizedArrayText;
  intro?: InternationalizedArrayText;
  highlights?: Array<{
    label?: InternationalizedArrayString;
    value?: InternationalizedArrayString;
    _type: "highlight";
    _key: string;
  }>;
  bodyEs?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  bodyEn?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  order?: number;
};

export type InternationalizedArrayTextValue = {
  _type: "internationalizedArrayTextValue";
  value?: string;
  language: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | CloudinaryAsset
  | SanityImageAssetReference
  | Agent
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayString
  | JournalPost
  | InternationalizedArrayText
  | Slug
  | Testimonial
  | NeighbourhoodReference
  | Property
  | Neighbourhood
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: PROPERTIES_QUERY
// Query: *[_type == "property" && isPublic == true] | order(price desc) {    _id,    "title": coalesce(      title[language == $locale][0].value,      title[language == "es"][0].value    ),    "slug": slug.current,    operation,    propertyType,    "neighbourhood": neighbourhood->name,    price,    surface,    bedrooms,    bathrooms,    "description": coalesce(      description[language == $locale][0].value,      description[language == "es"][0].value    ),    highlights,    "image": gallery[0]  }
export type PROPERTIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string;
  operation: "alquiler" | "venta";
  propertyType: "atico" | "casa" | "duplex" | "estudio" | "local" | "piso";
  neighbourhood: string;
  price: number;
  surface: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  description: string | null;
  highlights: Array<string> | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: AGENTS_QUERY
// Query: *[_type == "agent"] | order(order asc) {    _id,    name,    "title": coalesce(      title[language == $locale][0].value,      title[language == "es"][0].value    ),    email,    phone,    photo  }
export type AGENTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  title: string | null;
  email: string | null;
  phone: string;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: NEIGHBOURHOODS_QUERY
// Query: *[_type == "neighbourhood"] | order(order asc) {    _id,    name,    "slug": slug.current,    "blurb": coalesce(      blurb[language == $locale][0].value,      blurb[language == "es"][0].value    ),    image  }
export type NEIGHBOURHOODS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  blurb: string | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: NEIGHBOURHOOD_SLUGS_QUERY
// Query: *[_type == "neighbourhood" && defined(slug.current)] {    "slug": slug.current  }
export type NEIGHBOURHOOD_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: NEIGHBOURHOOD_BY_SLUG_QUERY
// Query: *[_type == "neighbourhood" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    "blurb": coalesce(      blurb[language == $locale][0].value,      blurb[language == "es"][0].value    ),    "intro": coalesce(      intro[language == $locale][0].value,      intro[language == "es"][0].value    ),    heroImage,    image,    gallery[]{ ... },    "highlights": highlights[]{      "label": coalesce(        label[language == $locale][0].value,        label[language == "es"][0].value      ),      "value": coalesce(        value[language == $locale][0].value,        value[language == "es"][0].value      )    },    "body": select(      $locale == "en" && defined(bodyEn) => bodyEn,      bodyEs    )  }
export type NEIGHBOURHOOD_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  blurb: string | null;
  intro: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  highlights: Array<{
    label: string | null;
    value: string | null;
  }> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PUBLISHED_TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && isPublished == true] | order(_createdAt desc) {    _id,    "quote": coalesce(      quote[language == $locale][0].value,      quote[language == "es"][0].value    ),    attribution  }
export type PUBLISHED_TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  quote: string | null;
  attribution: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROPERTY_SLUGS_QUERY
// Query: *[_type == "property" && isPublic == true && defined(slug.current)] {    "slug": slug.current  }
export type PROPERTY_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROPERTY_BY_SLUG_QUERY
// Query: *[_type == "property" && slug.current == $slug && isPublic == true][0] {    _id,    "title": coalesce(      title[language == $locale][0].value,      title[language == "es"][0].value    ),    "slug": slug.current,    price,    operation,    propertyType,    "neighbourhood": neighbourhood->name,    surface,    bedrooms,    bathrooms,    "description": coalesce(      description[language == $locale][0].value,      description[language == "es"][0].value    ),    highlights,    gallery[]{ ... },    isPublic  }
export type PROPERTY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string;
  price: number;
  operation: "alquiler" | "venta";
  propertyType: "atico" | "casa" | "duplex" | "estudio" | "local" | "piso";
  neighbourhood: string;
  surface: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  description: string | null;
  highlights: Array<string> | null;
  gallery: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  isPublic: boolean | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_POSTS_QUERY
// Query: *[_type == "journalPost" && isPublished == true && defined(slug.current)]    | order(publishedAt desc) {    _id,    "slug": slug.current,    category,    publishedAt,    author,    coverImage,    "title": coalesce(      title[language == $locale][0].value,      title[language == "es"][0].value    ),    "excerpt": coalesce(      excerpt[language == $locale][0].value,      excerpt[language == "es"][0].value    ),    "videoDuration": video.duration,    "videoPublicId": video.publicId,    videoPoster  }
export type JOURNAL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  category: "barrios" | "guias" | "interiorismo" | "inversion" | "lifestyle";
  publishedAt: string | null;
  author: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  title: string | null;
  excerpt: string | null;
  videoDuration: number | null;
  videoPublicId: string | null;
  videoPoster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: RECENT_JOURNAL_POSTS_QUERY
// Query: *[_type == "journalPost" && isPublished == true && defined(slug.current)]    | order(publishedAt desc)[0...3] {    _id,    "slug": slug.current,    category,    publishedAt,    coverImage,    "title": coalesce(      title[language == $locale][0].value,      title[language == "es"][0].value    ),    "excerpt": coalesce(      excerpt[language == $locale][0].value,      excerpt[language == "es"][0].value    ),    "videoDuration": video.duration,    "videoPublicId": video.publicId,    videoPoster  }
export type RECENT_JOURNAL_POSTS_QUERY_RESULT = Array<{
  _id: string;
  slug: string;
  category: "barrios" | "guias" | "interiorismo" | "inversion" | "lifestyle";
  publishedAt: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  title: string | null;
  excerpt: string | null;
  videoDuration: number | null;
  videoPublicId: string | null;
  videoPoster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_SLUGS_QUERY
// Query: *[_type == "journalPost" && isPublished == true && defined(slug.current)] {    "slug": slug.current  }
export type JOURNAL_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: JOURNAL_POST_BY_SLUG_QUERY
// Query: *[_type == "journalPost" && slug.current == $slug && isPublished == true][0] {    _id,    "slug": slug.current,    category,    publishedAt,    author,    coverImage,    "title": coalesce(      title[language == $locale][0].value,      title[language == "es"][0].value    ),    "excerpt": coalesce(      excerpt[language == $locale][0].value,      excerpt[language == "es"][0].value    ),    video,    videoPoster,    "videoCaption": coalesce(      videoCaption[language == $locale][0].value,      videoCaption[language == "es"][0].value    ),    "body": select(      $locale == "en" && defined(bodyEn) => bodyEn,      bodyEs    ),    isPublished  }
export type JOURNAL_POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  slug: string;
  category: "barrios" | "guias" | "interiorismo" | "inversion" | "lifestyle";
  publishedAt: string | null;
  author: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  title: string | null;
  excerpt: string | null;
  video: CloudinaryAsset | null;
  videoPoster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  videoCaption: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  > | null;
  isPublished: boolean | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "property" && isPublic == true] | order(price desc) {\n    _id,\n    "title": coalesce(\n      title[language == $locale][0].value,\n      title[language == "es"][0].value\n    ),\n    "slug": slug.current,\n    operation,\n    propertyType,\n    "neighbourhood": neighbourhood->name,\n    price,\n    surface,\n    bedrooms,\n    bathrooms,\n    "description": coalesce(\n      description[language == $locale][0].value,\n      description[language == "es"][0].value\n    ),\n    highlights,\n    "image": gallery[0]\n  }\n': PROPERTIES_QUERY_RESULT;
    '\n  *[_type == "agent"] | order(order asc) {\n    _id,\n    name,\n    "title": coalesce(\n      title[language == $locale][0].value,\n      title[language == "es"][0].value\n    ),\n    email,\n    phone,\n    photo\n  }\n': AGENTS_QUERY_RESULT;
    '\n  *[_type == "neighbourhood"] | order(order asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    "blurb": coalesce(\n      blurb[language == $locale][0].value,\n      blurb[language == "es"][0].value\n    ),\n    image\n  }\n': NEIGHBOURHOODS_QUERY_RESULT;
    '\n  *[_type == "neighbourhood" && defined(slug.current)] {\n    "slug": slug.current\n  }\n': NEIGHBOURHOOD_SLUGS_QUERY_RESULT;
    '\n  *[_type == "neighbourhood" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    "blurb": coalesce(\n      blurb[language == $locale][0].value,\n      blurb[language == "es"][0].value\n    ),\n    "intro": coalesce(\n      intro[language == $locale][0].value,\n      intro[language == "es"][0].value\n    ),\n    heroImage,\n    image,\n    gallery[]{ ... },\n    "highlights": highlights[]{\n      "label": coalesce(\n        label[language == $locale][0].value,\n        label[language == "es"][0].value\n      ),\n      "value": coalesce(\n        value[language == $locale][0].value,\n        value[language == "es"][0].value\n      )\n    },\n    "body": select(\n      $locale == "en" && defined(bodyEn) => bodyEn,\n      bodyEs\n    )\n  }\n': NEIGHBOURHOOD_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "testimonial" && isPublished == true] | order(_createdAt desc) {\n    _id,\n    "quote": coalesce(\n      quote[language == $locale][0].value,\n      quote[language == "es"][0].value\n    ),\n    attribution\n  }\n': PUBLISHED_TESTIMONIALS_QUERY_RESULT;
    '\n  *[_type == "property" && isPublic == true && defined(slug.current)] {\n    "slug": slug.current\n  }\n': PROPERTY_SLUGS_QUERY_RESULT;
    '\n  *[_type == "property" && slug.current == $slug && isPublic == true][0] {\n    _id,\n    "title": coalesce(\n      title[language == $locale][0].value,\n      title[language == "es"][0].value\n    ),\n    "slug": slug.current,\n    price,\n    operation,\n    propertyType,\n    "neighbourhood": neighbourhood->name,\n    surface,\n    bedrooms,\n    bathrooms,\n    "description": coalesce(\n      description[language == $locale][0].value,\n      description[language == "es"][0].value\n    ),\n    highlights,\n    gallery[]{ ... },\n    isPublic\n  }\n': PROPERTY_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "journalPost" && isPublished == true && defined(slug.current)]\n    | order(publishedAt desc) {\n    _id,\n    "slug": slug.current,\n    category,\n    publishedAt,\n    author,\n    coverImage,\n    "title": coalesce(\n      title[language == $locale][0].value,\n      title[language == "es"][0].value\n    ),\n    "excerpt": coalesce(\n      excerpt[language == $locale][0].value,\n      excerpt[language == "es"][0].value\n    ),\n    "videoDuration": video.duration,\n    "videoPublicId": video.publicId,\n    videoPoster\n  }\n': JOURNAL_POSTS_QUERY_RESULT;
    '\n  *[_type == "journalPost" && isPublished == true && defined(slug.current)]\n    | order(publishedAt desc)[0...3] {\n    _id,\n    "slug": slug.current,\n    category,\n    publishedAt,\n    coverImage,\n    "title": coalesce(\n      title[language == $locale][0].value,\n      title[language == "es"][0].value\n    ),\n    "excerpt": coalesce(\n      excerpt[language == $locale][0].value,\n      excerpt[language == "es"][0].value\n    ),\n    "videoDuration": video.duration,\n    "videoPublicId": video.publicId,\n    videoPoster\n  }\n': RECENT_JOURNAL_POSTS_QUERY_RESULT;
    '\n  *[_type == "journalPost" && isPublished == true && defined(slug.current)] {\n    "slug": slug.current\n  }\n': JOURNAL_SLUGS_QUERY_RESULT;
    '\n  *[_type == "journalPost" && slug.current == $slug && isPublished == true][0] {\n    _id,\n    "slug": slug.current,\n    category,\n    publishedAt,\n    author,\n    coverImage,\n    "title": coalesce(\n      title[language == $locale][0].value,\n      title[language == "es"][0].value\n    ),\n    "excerpt": coalesce(\n      excerpt[language == $locale][0].value,\n      excerpt[language == "es"][0].value\n    ),\n    video,\n    videoPoster,\n    "videoCaption": coalesce(\n      videoCaption[language == $locale][0].value,\n      videoCaption[language == "es"][0].value\n    ),\n    "body": select(\n      $locale == "en" && defined(bodyEn) => bodyEn,\n      bodyEs\n    ),\n    isPublished\n  }\n': JOURNAL_POST_BY_SLUG_QUERY_RESULT;
  }
}
